# Site Settings
title: Start Jekyll
email: oparcollet@flatironinstitute.org
description: >
  TEST
baseurl: ""
#url: "http://parcollet.github.io"
show_dir_listing: true
url: "http://localhost:4000"
#github_username:  parcollet
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
#theme: minima
